### ISSUE TITLE
Example dynamic Extension deployment Unresolved dependency

### ISSUE THREAD

**Issue by zafarale** [xenit-eu/example-dynamic-extension#2]
- What went wrong:
  Execution failed for task ':installBundle'.
  > Error installing bundle in repository: Unresolved constraint in bundle example-dynamic-extension [10]: Unable to resolve 10.0: missing requirement [10.0] osgi.wiring.package; (&(osgi.wiring.package=org.activiti.engine.delegate)(version>=5.7.0)(!(version>=6.0.0)))

**Comment by kerkhofsd** [comment]
Hi @zafarale , @alfrescian ,

This example project has been updated with the latest Dynamic Extensions version & is now build on Travis. The errors you faced shouldn't be there anymore. 

If you are still facing some issues with this project, don't hesitate to reopen / open another issue!
