### ISSUE TITLE
How to properly include external dependencies

### ISSUE THREAD

**Issue by karolbe** [xenit-eu/example-dynamic-extension#4]
Hi

Could you show in some example how to add external dependencies (defined in pom.xml or gradle.build) to an extension? I tried adding dependencies in an usual way but they wasn't visible by the code in the extension. I guess that since dynamic extensions are based on OSGi then standard Maven artifacts may not have the required manifest...? (sorry....I am OSGi noob)

Thanks!
Karol

**Comment by kerkhofsd** [comment]
Hi @karolbe ,

Even though this ticket has probably past it's expiry date, I'll try to answer your question :slightly_smiling_face: :

You should be able to declare dependencies 'the standard way': 

- Gradle: [declaring depedencies](https://docs.gradle.org/current/userguide/declaring_dependencies.html)
- Or in the standard `dependencies` block in you pom.xml if you are using Maven.

If your module requires runtime dependencies, you should make sure these dependencies are available in the Alfresco Platform.
