### ISSUE TITLE
[Question] Content bootstrapping

### ISSUE THREAD

**Issue by yregaieg** [xenit-eu/example-dynamic-extension#8]
Hello there,

I see here no example for bootstrapping content inside of "Data Dictionary" or the likes, but I thought that should be possible OOTB with Dynamic Extensions, anyway and example of that would be a great addition to this repo.

Regards,
Younes

**Comment by kerkhofsd** [comment]
Hi @yregaieg,

Thanks for your suggestion!
This functionality is indeed available in DE, however I did not yet use it myself. 

I had a quick look at adding this example based on [the documentation](https://github.com/xenit-eu/dynamic-extensions-for-alfresco/blob/master/documentation/Extension_Point_Bootstrap_Content.md). 
However the `BootstrapService` used for this purpose is part of the `annotations-runtime` submodule, which is considered internal API. I'll ask around with other team members that have used this functionality how it should be used. Nevertheless I am convinced that these examples should never have a dependency on the `annotations-runtime` internal dependency, hence we probably need to consider moving the `BootstrapService` to the public API.

Kind regards,
Daan

**Comment by kerkhofsd** [comment]
Hi @yregaieg,

FYI: I've created https://github.com/xenit-eu/dynamic-extensions-for-alfresco/issues/304

In my opinion we should avoid adding a dependency to `annotations-runtime` in the `example-dynamic-extension` project. Therefore I will not yet add a content bootstrapping example.

Kind regards,
Daan

**Comment by yregaieg** [comment]
Awesome, thanks! That documentation was exactly what I was looking for!

**Comment by yregaieg** [comment]
Again, thanks for the help guys!
I just wanted to share that BootstrapService doesn't seem to have automatic transaction wrapping, so I needed to add my own transaction wrapper, I have also needed to add myself a valid secure context, here is my code for future reference, should any other developer come across the same issue :
```
transactionService.getRetryingTransactionHelper().doInTransaction(() ->
      AuthenticationUtil.runAsSystem(() ->
        bootstrapService.deployResources(
          "osgibundle:/META-INF/alfresco/bootstrap/*.ftl",
          new RepositoryLocation(
            StoreRef.STORE_REF_WORKSPACE_SPACESSTORE,
            "/app:company_home/app:dictionary/app:email_templates",
            SearchService.LANGUAGE_XPATH
          ),
          new ContentCompareStrategy(resourceHelper),
          null, null, ContentModel.TYPE_CONTENT
        )
      ), false, true);
```
